services:
  openas2:
    image: greicodex/openas2:latest
    ports:
      - 4080:10080
      - 4081:10081
      - ${HOST_RESTAPI_PORT:-8443}:8080
    environment:
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__BASEURI=http://0.0.0.0:8080
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__USERID=admin
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__PASSWORD=admin123
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__ENABLED=true
      - OPENAS2PROP_msg_tracking__enabled=true
      - OPENAS2PROP_msg_tracking__use_embedded_db=true    
    tty: true
    stdin_open: true
    volumes:
      - ./config:/opt/openas2/config:rw
      - ./data:/opt/openas2/data:rw

  openas2_webui:
    image: greicodex/openas2-ui:latest
    environment:
        - VUE_APP_RESTAPI_URL=http://localhost:${HOST_RESTAPI_PORT:-8443}/api
    ports:
      - ${HOST_WEBUI_PORT:-8080}:80
    tty: true
    stdin_open: true
volumes:
  config:
  data: